test improvement

diff --git a/.tekton/task.yaml b/.tekton/task.yaml
--- a/.tekton/task.yaml
+++ b/.tekton/task.yaml
@@ -12,6 +12,6 @@ spec:
           apt-get -qq update > /dev/null; apt-get -qq -y install curl > /dev/null;
           alive=$(curl https://greenwell-app.eu-de.mybluemix.net/health);
           if [ "$alive" == "200 - Healthy" ];
-          then echo "TEST PASS"; exit 0;
-          else echo "TEST FAIL"; exit 1;
+          then echo "TEST PASS - 200"; exit 0;
+          else echo "TEST FAIL - $alive"; exit 1;
           fi
